export const actionTypes = {
   LOGGED_IN_USER : "LOGGED_IN_USER",
   MINT_COMPONENTS_DATA : "MINT_COMPONENTS_DATA",
   MINT_RESPONSE : "MINT_RESPONSE",
   MINT_PRODUCTS_DATA : "MINT_PRODUCTS_DATA",
   MINT_COMPONENT_FLAG : "MINT_COMPONENT_FLAG",
   MINT_PRODUCT_FLAG: "MINT_PRODUCT_FLAG" ,
   BURN_PRODUCT_FLAG: "BURN_PRODUCT_FLAG",
   BURN_COMPONENT_DATA: "BURN_COMPONENT_DATA",
   CHECK_BOX_VALUE: "CHECK_BOX_VALUE",
   ROLE_CHANGE : "ROLE_CHANGE",
   ADD_AS_A_CHILD: "ADD_AS_A_CHILD",
   ADD_AS_A_CHILD_BUTTON: "ADD_AS_A_CHILD_BUTTON",
   BURN_RESPONSE_DATA: "BURN_RESPONSE_DATA",
   ADD_AS_A_CHILD1: "ADD_AS_A_CHILD1",
   MINT_PRODUCTS_PRODUCE_DATA: "MINT_PRODUCTS_PRODUCE_DATA"
}