export const actionTypes = {
   LOGGED_IN_USER : "LOGGED_IN_USER",
   MINT_COMPONENTS_DATA : "MINT_COMPONENTS_DATA",
   MINT_RESPONSE : "MINT_RESPONSE",
   MINT_PRODUCTS_DATA : "MINT_PRODUCTS_DATA",
   MINT_COMPONENT_FLAG : "MINT_COMPONENT_FLAG",
   MINT_PRODUCT_FLAG: "MINT_PRODUCT_FLAG" ,
   BURN_PRODUCT_FLAG: "BURN_PRODUCT_FLAG",
   BURN_COMPONENT_DATA: "BURN_COMPONENT_DATA",
   CHECK_BOX_VALUE: "CHECK_BOX_VALUE",
   ROLE_CHANGE : "ROLE_CHANGE"
}